dsf_dtype_dict = {
    'DisFacPr': 'float64',
    'DisFacShr': 'float64',
    'DlyAsk': 'float64',
    'DlyBid': 'float64',
    'DlyCap': 'float64',
    'DlyCapFlg': 'object',
    'DlyClose': 'float64',
    'DlyDelFlg': 'object',
    'DlyDistRetFlg': 'object',
    'DlyFacPrc': 'float64',
    'DlyHigh': 'float64',
    'DlyLow': 'float64',
    'DlyMMCnt': 'float64',
    'DlyNonOrdDivAmt': 'float64',
    'DlyNumTrd': 'float64',
    'DlyOpen': 'float64',
    'DlyOrdDivAmt': 'float64',
    'DlyPrc': 'float64',
    'DlyPrcFlg': 'object',
    'DlyPrcVol': 'float64',
    'DlyPrevCap': 'float64',
    'DlyPrevCapFlg': 'object',
    'DlyPrevPrc': 'float64',
    'DlyPrevPrcFlg': 'object',
    'DlyRet': 'float64',
    'DlyRetDurFlg': 'object',
    'DlyRetI': 'float64',
    'DlyRetMissFlg': 'object',
    'DlyRetx': 'float64',
    'DlyVol': 'float64',
    'HdrCUSIP': 'object',
    'NASDIssuno': 'float64',
    'PERMCO': 'float64',
    'PERMNO': 'int64',
    'ShrOut': 'float64',
    'SICCD': 'float64',
    'YYYYMMDD': 'float64'
}

dsp500_list_dict = {
    'ndfam': 'float64',
    'indno': 'float64',
    'mbrflg': 'object',
    'permno': 'int64',
}
